// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uytgtctziuemthupfnjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5dGd0Y3R6aXVlbXRodXBmbmpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTM5NzAsImV4cCI6MjA1ODI4OTk3MH0.-L76j86T1Hf8Di5dyOYI3Qqg-9vrcpIJAbdzNFwY9t0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);